// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCnZ_kVsr58mPkvxm3TMEFRr9oXf3GIo9Y',
    appId: '1:487169445894:web:426346a93eb98d322a3387',
    messagingSenderId: '487169445894',
    projectId: 'shopping-list-app-7641f',
    authDomain: 'shopping-list-app-7641f.firebaseapp.com',
    databaseURL: 'https://shopping-list-app-7641f-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-list-app-7641f.firebasestorage.app',
    measurementId: 'G-1NBHZ94FEE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAtuKELBQ_jirYVlYJkT71aNCCNze2-grM',
    appId: '1:487169445894:android:faf24bf0a21701192a3387',
    messagingSenderId: '487169445894',
    projectId: 'shopping-list-app-7641f',
    databaseURL: 'https://shopping-list-app-7641f-default-rtdb.firebaseio.com',
    storageBucket: 'shopping-list-app-7641f.firebasestorage.app',
  );
}
